#version 450

#define BODIES_COUNT 6144

layout (local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

struct Body {
	vec3 position;
	vec3 last_position;
	vec3 velocity;
	float mass;
};

layout (set = 0, binding = 0) buffer buf_block {
	Body bodies[BODIES_COUNT];
};


void main() {
	// index for itself
	uint index = gl_GlobalInvocationID.x;

	if(index >= BODIES_COUNT)
		return;
	
	bodies[index].last_position = bodies[index].position;
}